spring:
  datasource:
    url: jdbc:mysql://localhost/food_recipe
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ture
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

server:
  port: 9090